FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS base
RUN apk add tzdata
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://*:8080

FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
WORKDIR /src
COPY ["book-a-reading-room-visit.web/book-a-reading-room-visit.web.csproj", "book-a-reading-room-visit.web/"]
RUN dotnet restore "book-a-reading-room-visit.web/book-a-reading-room-visit.web.csproj"
COPY . .
WORKDIR "/src/book-a-reading-room-visit.web"
RUN dotnet build "book-a-reading-room-visit.web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "book-a-reading-room-visit.web.csproj" -c Release -o /app/publish

FROM base AS final
RUN addgroup -g 965 -S appuser && adduser -u 975 -S -D -h /app appuser appuser
USER appuser
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "book-a-reading-room-visit.web.dll"]