FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS base
RUN apk add tzdata
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
WORKDIR /src
COPY ["book-a-reading-room-visit.web/book-a-reading-room-visit.web.csproj", "book-a-reading-room-visit.web/"]
RUN dotnet restore "book-a-reading-room-visit.web/book-a-reading-room-visit.web.csproj"
COPY . .
WORKDIR "/src/book-a-reading-room-visit.web"
RUN dotnet build "book-a-reading-room-visit.web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "book-a-reading-room-visit.web.csproj" -c Release -o /app/publish

FROM base AS final
RUN adduser \
  --disabled-password \
  --home /app \
  --gecos '' app \
  && chown -R app /app
USER app
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "book-a-reading-room-visit.web.dll"]