USE [master]
GO

/****** Object:  Database [Logging]    Script Date: 10/11/2021 17:55:05 ******/
CREATE DATABASE [Logging]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Logging', FILENAME = N'D:\rdsdbdata\DATA\Logging.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Logging_log', FILENAME = N'D:\rdsdbdata\DATA\Logging_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Logging].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Logging] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Logging] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Logging] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Logging] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Logging] SET ARITHABORT OFF 
GO

ALTER DATABASE [Logging] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Logging] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Logging] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Logging] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Logging] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Logging] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Logging] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Logging] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Logging] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Logging] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Logging] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Logging] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Logging] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Logging] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Logging] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Logging] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Logging] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Logging] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Logging] SET  MULTI_USER 
GO

ALTER DATABASE [Logging] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Logging] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Logging] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Logging] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Logging] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Logging] SET QUERY_STORE = OFF
GO

USE [Logging]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [Logging] SET  READ_WRITE 
GO


