//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanceOrderServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentReference", Namespace="http://schemas.datacontract.org/2004/07/NationalArchives.AdvancedOrders.BusinessO" +
        "bjects")]
    public partial class DocumentReference : object
    {
        
        private AdvanceOrderServiceReference.DocumentParts DocPartsField;
        
        private AdvanceOrderServiceReference.DocumentRefCodes ReturnStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdvanceOrderServiceReference.DocumentParts DocParts
        {
            get
            {
                return this.DocPartsField;
            }
            set
            {
                this.DocPartsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdvanceOrderServiceReference.DocumentRefCodes ReturnStatus
        {
            get
            {
                return this.ReturnStatusField;
            }
            set
            {
                this.ReturnStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentParts", Namespace="http://schemas.datacontract.org/2004/07/NationalArchives.AdvancedOrders.BusinessO" +
        "bjects")]
    public partial class DocumentParts : object
    {
        
        private string ClosureStatusField;
        
        private string DocumentReferenceTextField;
        
        private int ItemIdField;
        
        private string ItemRefField;
        
        private int PieceIdField;
        
        private string PieceRefField;
        
        private int ReturnStatusField;
        
        private string ScopeField;
        
        private int SubClassField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClosureStatus
        {
            get
            {
                return this.ClosureStatusField;
            }
            set
            {
                this.ClosureStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentReferenceText
        {
            get
            {
                return this.DocumentReferenceTextField;
            }
            set
            {
                this.DocumentReferenceTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId
        {
            get
            {
                return this.ItemIdField;
            }
            set
            {
                this.ItemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemRef
        {
            get
            {
                return this.ItemRefField;
            }
            set
            {
                this.ItemRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PieceId
        {
            get
            {
                return this.PieceIdField;
            }
            set
            {
                this.PieceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PieceRef
        {
            get
            {
                return this.PieceRefField;
            }
            set
            {
                this.PieceRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReturnStatus
        {
            get
            {
                return this.ReturnStatusField;
            }
            set
            {
                this.ReturnStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Scope
        {
            get
            {
                return this.ScopeField;
            }
            set
            {
                this.ScopeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubClass
        {
            get
            {
                return this.SubClassField;
            }
            set
            {
                this.SubClassField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentRefCodes", Namespace="http://schemas.datacontract.org/2004/07/NationalArchives.AdvancedOrders.BusinessO" +
        "bjects")]
    public enum DocumentRefCodes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_VALID = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_INVALID_LETTER_CODE_OR_CLASS = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_INVALID_SUBCLASS = -2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_NO_ROWS_FOUND = -3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_MULITIPLE_ROWS_FOUND = -4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_INVALID_LETTER_CODE = -5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_UN_ORDERABLE = -6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_CLOSED = -7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_OFFSITE = -8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_KEW_SURROGATE = -9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_UNFIT = -10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_MISSING = -11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_DIGITAL_SURROGATE_AVAILABLE = -12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_NOT_HELD_AT_KEW = -13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_RELOCATION = -14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_COLLECTION_CARE = -15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_ON_LOAN = -16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_ON_DISPLAY = -17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_ON_MOULD_TREATMENT = -18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_NO_PATTERN_MATCH = -19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOCUMENT_REFERENCE_NULL = -20,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdvancedOrder", Namespace="http://schemas.datacontract.org/2004/07/NationalArchives.AdvancedOrders.BusinessO" +
        "bjects")]
    public partial class AdvancedOrder : object
    {
        
        private System.DateTime DateRequiredField;
        
        private int DocumentNotAtKewField;
        
        private string DocumentReferenceField;
        
        private string FullNameField;
        
        private int OrderNumberField;
        
        private int PieceIdField;
        
        private int ReaderTicketField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateRequired
        {
            get
            {
                return this.DateRequiredField;
            }
            set
            {
                this.DateRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentNotAtKew
        {
            get
            {
                return this.DocumentNotAtKewField;
            }
            set
            {
                this.DocumentNotAtKewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentReference
        {
            get
            {
                return this.DocumentReferenceField;
            }
            set
            {
                this.DocumentReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PieceId
        {
            get
            {
                return this.PieceIdField;
            }
            set
            {
                this.PieceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReaderTicket
        {
            get
            {
                return this.ReaderTicketField;
            }
            set
            {
                this.ReaderTicketField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReaderDetails", Namespace="http://schemas.datacontract.org/2004/07/NationalArchives.AdvancedOrders.BusinessO" +
        "bjects")]
    public partial class ReaderDetails : object
    {
        
        private string NameField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VisitorDetails", Namespace="http://schemas.datacontract.org/2004/07/NationalArchives.AdvancedOrders.BusinessO" +
        "bjects")]
    public partial class VisitorDetails : object
    {
        
        private string EmailField;
        
        private string FirstnameField;
        
        private string LastnameField;
        
        private string PhoneField;
        
        private System.Nullable<int> ReaderTicketField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname
        {
            get
            {
                return this.FirstnameField;
            }
            set
            {
                this.FirstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname
        {
            get
            {
                return this.LastnameField;
            }
            set
            {
                this.LastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReaderTicket
        {
            get
            {
                return this.ReaderTicketField;
            }
            set
            {
                this.ReaderTicketField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentOrder", Namespace="http://schemas.datacontract.org/2004/07/NationalArchives.AdvancedOrders.BusinessO" +
        "bjects")]
    public partial class DocumentOrder : object
    {
        
        private int CurrentOrdersField;
        
        private int OrderCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentOrders
        {
            get
            {
                return this.CurrentOrdersField;
            }
            set
            {
                this.CurrentOrdersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderCount
        {
            get
            {
                return this.OrderCountField;
            }
            set
            {
                this.OrderCountField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservationType", Namespace="http://schemas.datacontract.org/2004/07/NationalArchives.AdvancedOrders.BusinessO" +
        "bjects")]
    public enum ReservationType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReadingRoomWithoutCamera = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReadingRoomWithCamera = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MapRoom = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BulkOrder = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeatAvailable", Namespace="http://schemas.datacontract.org/2004/07/NationalArchives.AdvancedOrders.BusinessO" +
        "bjects")]
    public partial class SeatAvailable : object
    {
        
        private int ErrorField;
        
        private int SeatIdField;
        
        private string SeatNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeatId
        {
            get
            {
                return this.SeatIdField;
            }
            set
            {
                this.SeatIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeatNumber
        {
            get
            {
                return this.SeatNumberField;
            }
            set
            {
                this.SeatNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeatReservation", Namespace="http://schemas.datacontract.org/2004/07/NationalArchives.AdvancedOrders.BusinessO" +
        "bjects")]
    public partial class SeatReservation : object
    {
        
        private int ErrorField;
        
        private System.DateTime ReservationDateField;
        
        private int SeatIdField;
        
        private AdvanceOrderServiceReference.ReservationType SeatTypeField;
        
        private System.Nullable<char> StatusField;
        
        private int UserIdField;
        
        private int UserTicketField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReservationDate
        {
            get
            {
                return this.ReservationDateField;
            }
            set
            {
                this.ReservationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SeatId
        {
            get
            {
                return this.SeatIdField;
            }
            set
            {
                this.SeatIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdvanceOrderServiceReference.ReservationType SeatType
        {
            get
            {
                return this.SeatTypeField;
            }
            set
            {
                this.SeatTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<char> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserTicket
        {
            get
            {
                return this.UserTicketField;
            }
            set
            {
                this.UserTicketField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservationResult", Namespace="http://schemas.datacontract.org/2004/07/NationalArchives.AdvancedOrders.BusinessO" +
        "bjects")]
    public partial class ReservationResult : object
    {
        
        private string ErrorMessageField;
        
        private string SeatNumberField;
        
        private bool SucessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeatNumber
        {
            get
            {
                return this.SeatNumberField;
            }
            set
            {
                this.SeatNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sucess
        {
            get
            {
                return this.SucessField;
            }
            set
            {
                this.SucessField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdvanceOrderServiceReference.IAdvancedOrderService")]
    public interface IAdvancedOrderService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedOrderService/ValidateDocumentReference", ReplyAction="http://tempuri.org/IAdvancedOrderService/ValidateDocumentReferenceResponse")]
        System.Threading.Tasks.Task<AdvanceOrderServiceReference.DocumentReference> ValidateDocumentReferenceAsync(string docReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedOrderService/SaveAdvancedOrder", ReplyAction="http://tempuri.org/IAdvancedOrderService/SaveAdvancedOrderResponse")]
        System.Threading.Tasks.Task<bool> SaveAdvancedOrderAsync(AdvanceOrderServiceReference.AdvancedOrder advancedOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedOrderService/IsTNAClosed", ReplyAction="http://tempuri.org/IAdvancedOrderService/IsTNAClosedResponse")]
        System.Threading.Tasks.Task<bool> IsTNAClosedAsync(System.DateTime startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedOrderService/IsTNAHoliday", ReplyAction="http://tempuri.org/IAdvancedOrderService/IsTNAHolidayResponse")]
        System.Threading.Tasks.Task<bool> IsTNAHolidayAsync(System.DateTime selectedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedOrderService/IsEventbriteOrderNumberUsed", ReplyAction="http://tempuri.org/IAdvancedOrderService/IsEventbriteOrderNumberUsedResponse")]
        System.Threading.Tasks.Task<bool> IsEventbriteOrderNumberUsedAsync(int orderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedOrderService/ThreeWorkingDays", ReplyAction="http://tempuri.org/IAdvancedOrderService/ThreeWorkingDaysResponse")]
        System.Threading.Tasks.Task<System.DateTime> ThreeWorkingDaysAsync(System.Nullable<System.DateTime> endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedOrderService/IsReaderTicketValid", ReplyAction="http://tempuri.org/IAdvancedOrderService/IsReaderTicketValidResponse")]
        System.Threading.Tasks.Task<bool> IsReaderTicketValidAsync(string readerTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedOrderService/GetReaderDetailsByTicketNo", ReplyAction="http://tempuri.org/IAdvancedOrderService/GetReaderDetailsByTicketNoResponse")]
        System.Threading.Tasks.Task<AdvanceOrderServiceReference.ReaderDetails> GetReaderDetailsByTicketNoAsync(string readerTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedOrderService/GetVisitorDetailsByTicketNo", ReplyAction="http://tempuri.org/IAdvancedOrderService/GetVisitorDetailsByTicketNoResponse")]
        System.Threading.Tasks.Task<AdvanceOrderServiceReference.VisitorDetails> GetVisitorDetailsByTicketNoAsync(string readerTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedOrderService/AdvancedOrderCheck", ReplyAction="http://tempuri.org/IAdvancedOrderService/AdvancedOrderCheckResponse")]
        System.Threading.Tasks.Task<AdvanceOrderServiceReference.DocumentOrder> AdvancedOrderCheckAsync(string readerTicket, System.DateTime dateofVisit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedOrderService/GetAvailableSeat", ReplyAction="http://tempuri.org/IAdvancedOrderService/GetAvailableSeatResponse")]
        System.Threading.Tasks.Task<AdvanceOrderServiceReference.SeatAvailable> GetAvailableSeatAsync(AdvanceOrderServiceReference.ReservationType reservationType, System.DateTime reservationDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdvancedOrderService/ReserveSeat", ReplyAction="http://tempuri.org/IAdvancedOrderService/ReserveSeatResponse")]
        System.Threading.Tasks.Task<AdvanceOrderServiceReference.ReservationResult> ReserveSeatAsync(AdvanceOrderServiceReference.SeatReservation seatReservation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IAdvancedOrderServiceChannel : AdvanceOrderServiceReference.IAdvancedOrderService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AdvancedOrderServiceClient : System.ServiceModel.ClientBase<AdvanceOrderServiceReference.IAdvancedOrderService>, AdvanceOrderServiceReference.IAdvancedOrderService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AdvancedOrderServiceClient() : 
                base(AdvancedOrderServiceClient.GetDefaultBinding(), AdvancedOrderServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAdvancedOrderService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdvancedOrderServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AdvancedOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), AdvancedOrderServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdvancedOrderServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AdvancedOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdvancedOrderServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AdvancedOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AdvancedOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AdvanceOrderServiceReference.DocumentReference> ValidateDocumentReferenceAsync(string docReference)
        {
            return base.Channel.ValidateDocumentReferenceAsync(docReference);
        }
        
        public System.Threading.Tasks.Task<bool> SaveAdvancedOrderAsync(AdvanceOrderServiceReference.AdvancedOrder advancedOrder)
        {
            return base.Channel.SaveAdvancedOrderAsync(advancedOrder);
        }
        
        public System.Threading.Tasks.Task<bool> IsTNAClosedAsync(System.DateTime startDate)
        {
            return base.Channel.IsTNAClosedAsync(startDate);
        }
        
        public System.Threading.Tasks.Task<bool> IsTNAHolidayAsync(System.DateTime selectedDate)
        {
            return base.Channel.IsTNAHolidayAsync(selectedDate);
        }
        
        public System.Threading.Tasks.Task<bool> IsEventbriteOrderNumberUsedAsync(int orderNumber)
        {
            return base.Channel.IsEventbriteOrderNumberUsedAsync(orderNumber);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> ThreeWorkingDaysAsync(System.Nullable<System.DateTime> endDate)
        {
            return base.Channel.ThreeWorkingDaysAsync(endDate);
        }
        
        public System.Threading.Tasks.Task<bool> IsReaderTicketValidAsync(string readerTicket)
        {
            return base.Channel.IsReaderTicketValidAsync(readerTicket);
        }
        
        public System.Threading.Tasks.Task<AdvanceOrderServiceReference.ReaderDetails> GetReaderDetailsByTicketNoAsync(string readerTicket)
        {
            return base.Channel.GetReaderDetailsByTicketNoAsync(readerTicket);
        }
        
        public System.Threading.Tasks.Task<AdvanceOrderServiceReference.VisitorDetails> GetVisitorDetailsByTicketNoAsync(string readerTicket)
        {
            return base.Channel.GetVisitorDetailsByTicketNoAsync(readerTicket);
        }
        
        public System.Threading.Tasks.Task<AdvanceOrderServiceReference.DocumentOrder> AdvancedOrderCheckAsync(string readerTicket, System.DateTime dateofVisit)
        {
            return base.Channel.AdvancedOrderCheckAsync(readerTicket, dateofVisit);
        }
        
        public System.Threading.Tasks.Task<AdvanceOrderServiceReference.SeatAvailable> GetAvailableSeatAsync(AdvanceOrderServiceReference.ReservationType reservationType, System.DateTime reservationDate)
        {
            return base.Channel.GetAvailableSeatAsync(reservationType, reservationDate);
        }
        
        public System.Threading.Tasks.Task<AdvanceOrderServiceReference.ReservationResult> ReserveSeatAsync(AdvanceOrderServiceReference.SeatReservation seatReservation)
        {
            return base.Channel.ReserveSeatAsync(seatReservation);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAdvancedOrderService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAdvancedOrderService))
            {
                return new System.ServiceModel.EndpointAddress("http://172.31.2.125/AdvancedOrderService/AdvancedOrderService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AdvancedOrderServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAdvancedOrderService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AdvancedOrderServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAdvancedOrderService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAdvancedOrderService,
        }
    }
}
