permissions:
      id-token: write
      contents: write 

on:
  push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  workflow_dispatch:
    inputs:
      kbs-web-version-tag:
        description: 'KBS Web version Tag'     
        required: true
        default: 'latest'
      kbs-api-version-tag:
        description: 'KBS API version Tag'     
        required: true
        default: 'latest'


name: KBS Build and Push API & Web 

jobs:
  Docker:
    name: Docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::500447081210:role/github-oidc-Role-MCT2KM9AM6YN
          role-session-name: MySessionName

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push the API to ECR
      id: build-push-API
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: kbs-api
        IMAGE_TAG: ${{ github.event.inputs.kbs-api-version-tag }}
      run: |
        # Build the API docker container and push it to ECR 
        docker build -t 500447081210.dkr.ecr.eu-west-2.amazonaws.com/kbs-api:latest .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
    - name: Build, tag, and push the Web to ECR
      id: build-push-Web
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.WEB_REPO_NAME }}
        IMAGE_TAG: ${{ github.event.inputs.kbs-web-version-tag }}
      run: |
        # Build the Web docker container and push it to ECR 
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"